### ISSUE TITLE
Add support for a command line companion tool for Anzii

### ISSUE THREAD

**Issue by ntsakosurprise** [iiprodakts/anzii#1]
I usually prefer to scaffold or bootstrap my applications with the same template that I first used to success, this usually saves me a lot of time as I do not have to do the repetitive tasks that are similar for each project such as a project structure. 

It also helps me a lot to have configuration files such as .gitignore,webpack.config.js,etc automatically generated to simplify my configuration effort(if any at all).

I read the introductory guidelines of anzii and realized that there are some tasks that users of the framework have to perform in using the framework such as creating a .config.js file. 

I think it would be nice if anzii had a tool to automate tasks like the aforementioned for users so that they can focus on building with anzii out of the box instead of focusing on configurations.

I'm a coding enthusiast who enjoys working on open source projects, and I would love to work on this feature,it's also worth noting that I understand anzii as well as the philosophy behind it, so building this feature will be another way for me to dive deep into the project.

Thanks for a great product!

**Comment by iiprodakts** [comment]
Hi ntsakosurprise,

We appreciate your effort to be part of this project, 
we are grateful that you are willing to help it grow. As per your request, we will joyfully assign this task to you.

This is a great feature to add to the anzii ecosystem indeed, this is something that we had also thought about in the past, and
this feature request has made us re-focus on tooling efforts for anzii. 

In the past, we had also thought about building a cli plugin as a kind of framework to help users like yourself who want to develop cli programs do 
it quicker with the tool they already know(if they know anzii). For your case, this could be very helpful.

We intend to start work on the cli program outright(anzii-make-cli as a working title),you can start working on the requested feature outright, bu it 
if you prefer, you can wait until we are done with this to use it for your project.

Thanks in advance for your effort.

**Comment by ntsakosurprise** [comment]
I appreciate you assigning the task to me as per my request,I'll see to it that I get started with it. As for the intended cli plugin (anzii-make-cli),I'm really interested in building with that,but in the meantime,I'll just start working on it,and just update my plugin to use that. 

Thanks once again for allowing me the opportunity to build the CLI tool.
